language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest tests --cov=fgspectra

# Push the results back to codecov
after_success:
  - codecov